package me.twocities.linker

import me.twocities.linker.annotations.Link

/**
 * Parse the given link as [LinkMetadata]
 *
 * [LinkParser]'s implementation is generated by compiler, and the implementation
 * is used by the generated [LinkResolver] builder.
 */
interface LinkParser {
  /**
   * Parse `link` into [LinkMetadata]
   *
   * @return an AppLinkMeta contains the link's information,
   * or null if Activities annotated with [Link] cannot match `link`
   */
  fun parse(link: String): LinkMetadata?
}